### ISSUE TITLE
L2O Experiments

### ISSUE THREAD

**Issue by ps4vs** [mkofinas/neural-graphs#1]
Hey @mkofinas, could you please share L2O experiments?

**Comment by mkofinas** [comment]
Hi @ps4vs, thank you for your interest in our work! I haven't cleaned up the code for the L2O experiments yet. I plan to do so in the following 2-3 weeks. In the meantime, the code is already available in the supplementary material of the paper in OpenReview: https://openreview.net/attachment?id=oO6FsMyDBt&name=supplementary_material.

**Comment by ps4vs** [comment]
Thanks @mkofinas, code available in supplementary material will be good for me.
