### ISSUE TITLE
Small CNN Zoo Configurations

### ISSUE THREAD

**Issue by Kausta** [mkofinas/neural-graphs#2]
Hello @mkofinas, would it be possible for you to share the exact configurations/scripts used to calculate the NG-GNN and NG-T results in Table 1, Column CIFAR10-GS? There were multiple versions (scripts folder in this repo vs. README.md in cnn_generalization vs. scripts folder in the supplementary material at OpenReview vs. the details shared in the paper). 

(Btw, amazing work!)

**Comment by mkofinas** [comment]
Hello @Kausta, thank you for your kind words, and apologies for the lack of clarity regarding the configurations.

The scripts and the README in `cnn_generalization`, as well as the details shared in the paper, all used to refer to the CNN Wild Park experiment. Apparently, we had omitted sharing the configurations regarding CIFAR10-GS.

I have now uploaded the scripts to reproduce the results from Table 1 for CIFAR10-GS. You can find them at:
- [`.experiments/cnn_generalization/scripts/cnn_zoo_rt.sh`](https://github.com/mkofinas/neural-graphs/blob/main/experiments/cnn_generalization/scripts/cnn_zoo_rt.sh)
- [`.experiments/cnn_generalization/scripts/cnn_zoo_pna.sh`](https://github.com/mkofinas/neural-graphs/blob/main/experiments/cnn_generalization/scripts/cnn_zoo_pna.sh)

I will also update the paper on arXiv with these hyperparameters. Please let me know if you have any further questions.

**Comment by Kausta** [comment]
Thanks @mkofinas
